service: personal-finance-app

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  auth:
    handler: auth.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true
      - http:
          path: auth/signup
          method: post
          cors: true
      - http:
          path: auth/verify
          method: post
          cors: true

  budgets:
    handler: budgets.handler
    events:
      - http:
          path: budgets
          method: get
          cors: true
      - http:
          path: budgets/{id}
          method: get
          cors: true
      - http:
          path: budgets
          method: post
          cors: true
      - http:
          path: budgets/{id}
          method: put
          cors: true
      - http:
          path: budgets/{id}
          method: delete
          cors: true

  transactions:
    handler: transactions.handler
    events:
      - http:
          path: transactions
          method: get
          cors: true
      - http:
          path: transactions/{id}
          method: get
          cors: true
      - http:
          path: transactions
          method: post
          cors: true
      - http:
          path: transactions/{id}
          method: put
          cors: true
      - http:
          path: transactions/{id}
          method: delete
          cors: true

  pots:
    handler: pots.handler
    events:
      - http:
          path: pots
          method: get
          cors: true
      - http:
          path: pots/{id}
          method: get
          cors: true
      - http:
          path: pots
          method: post
          cors: true
      - http:
          path: pots/{id}
          method: put
          cors: true
      - http:
          path: pots/{id}
          method: delete
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true
