functions:
  auth:
    handler: api/auth/index.handler
    events:
      - http:
          path: api/auth/signup
          method: post
          cors: true
      - http:
          path: api/auth/login
          method: post
          cors: true
      - http:
          path: api/auth/verify
          method: post
          cors: true
